# _config.yml (Revised - Option A: Using the theme)

title: "GuRuTuX" # Or a more specific title
url: "https://gurutux.com" # Replace with your actual site URL
baseurl: "" # Set to /repository-name if applicable, otherwise leave empty

description: "Technical articles and analysis on software engineering and system design." # Example: More precise description
# show_downloads: true # Verify if theme uses this. If not, remove.

markdown: GFM
# google_analytics: UA-XXXXX-Y # Uncomment and replace if you use GA

# theme: jekyll-theme-hacker 

# Optional: Add theme-specific configuration variables here if jekyll-theme-hacker supports them. Check its documentation.

# Plugins often used with Jekyll/GitHub Pages (add jekyll-feed if you want an RSS feed)
# plugins:
#   - jekyll-feed
